name: Documentaci贸n Pdoc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  generate-docs-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar pdoc
        run: pip install -U pdoc

      - name: Generar documentaci贸n HTML con pdoc
        run: |
          mkdir -p docs/html
          pdoc main.py src/ --output-dir docs/html

      - name: Generar documentaci贸n Markdown
        run: |
          mkdir -p docs/md
          pdoc -d markdown main.py src/ -o docs/md

      - name: Commit y push 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizaci贸n"
          file_pattern: "docs/html/*"
          branch: main
